name: njsscan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:      
  npmAudit:
    runs-on: ubuntu-latest
    name: npmAudit library scanning
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: npmAudit scan
      run : |
        echo "hello"
    - name: Upload npmAudit report
      run : |
        echo "Hii"
      env:
        URL: ${{ secrets.URL}}
        KEY: ${{ secrets.KEY }}

