name: nodejs

on:
  push:

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Uploading the SAST results
      run: |
        pip install njsscan  
        njsscan path $PWD --sarif --output nodejs-report.sarif
        curl -X 'POST' \
        'http://170.187.141.105:8080/api/v2/reimport-scan/' \
        -H 'accept: application/json' \
        -H 'Authorization: Token 6aa3f54c2bd91951c7945dac26a8065a2314580c' \
        -H 'Content-Type: multipart/form-data' \
        -F 'test=3' \
        -F '[email protected];type=application/json' \
        -F file=@"nodejs-report.sarif" \
        -F 'scan_type=SARIF' \
        -F 'tags=test'
        

