name: njsscan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan code scanning
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '. --sarif --output results.sarif || true'
    - name: Upload njsscan report
      run : |
        cat results.sarif
        curl -X 'POST' \
        'http://170.187.141.105:8080/api/v2/reimport-scan/' \
        -H 'accept: application/json' \
        -H 'Authorization: Token 6aa3f54c2bd91951c7945dac26a8065a2314580c' \
        -H 'Content-Type: multipart/form-data' \
        -F 'test=3' \
        -F '[email protected];type=application/json' \
        -F file=@"results.sarif" \
        -F 'scan_type=SARIF' \
        -F 'tags=test'
      env:
        URL: ${{ secrets.URL}}
        KEY: ${{ secrets.KEY }}

  npmAudit:
    runs-on: ubuntu-latest
    name: npmAudit library scanning
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: npmAudit scan
      run : |
        curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        sudo apt-get install -y nodejs
    - name: Upload npmAudit report
      run : |
        npm i --package-lock-only
        npm audit --json >> npm_result.json | true
        cat npm_result.json
        curl -X 'POST' \
        'http://170.187.141.105:8080/api/v2/reimport-scan/' \
        -H 'accept: application/json' \
        -H 'Authorization: Token 6aa3f54c2bd91951c7945dac26a8065a2314580c' \
        -H 'Content-Type: multipart/form-data' \
        -F 'test=4' \
        -F '[email protected];type=application/json' \
        -F file=@"npm_result.json" \
        -F 'scan_type=NPM Audit Scan' \
        -F 'tags=test'
      env:
        URL: ${{ secrets.URL}}
        KEY: ${{ secrets.KEY }}
