name: nodejs

on:
  push:

jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Uploading the SAST results
      run: |
        pip install nodejsscan  
        nodejsscan path $PWD --sarif --output nodejs-report.sarif | true

